const data = {
  "status": "OK",
  "request_id": "4711e4c8-e886-4a27-a2bb-6e27053d10cc",
  "parameters": {
    "query": "web developer ontario",
    "page": 1,
    "num_pages": 1
  },
  "data": [
    {
      "employer_name": "2441104 ONTARIO INC.",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "Job Bank",
      "job_id": "P9FrwFQjfz0od0DlAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Web developer     Verified",
      "job_apply_link": "https://www.jobbank.gc.ca/jobsearch/jobposting/39204291",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.8515,
      "apply_options": [
        {
          "publisher": "Job Bank",
          "apply_link": "https://www.jobbank.gc.ca/jobsearch/jobposting/39204291",
          "is_direct": false
        }
      ],
      "job_description": "Education: College, CEGEP or other non-university certificate or diploma from a program of 1 year to 2 years. Information technology. Computer science. Engineering-related fields, other. Work setting: Consulting firm. Tasks: Prepare mock-ups and storyboards. Develop Website architecture and determine hardware and software requirements. Source, select and organize information for inclusion and design the appearance, layout and flow of the Website. Create and optimize content for Website using a variety of graphics, database, animation and other software. Lead and co-ordinate multidisciplinary teams to develop Website graphics, content, capacity and interactivity. Conduct tests and perform security and quality controls. Plan, design, write, modify, integrate and test Web-site related code. Write, modify, integrate and test software code. Identify and communicate technical problems, processes and solutions. Prepare reports, manuals and other documentation on the status, operation and maintenance of software. Assist in the collection and documentation of user's requirements. Assist in the development of logical and physical specifications. Research and evaluate a variety of software products. Maintain existing computer programs by making modifications as required. Write, modify, integrate and test software code for e-commerce and other Internet applications. Computer and technology knowledge: HTML editing software. Web service design. MS Office. MS Excel. WordPress. Work conditions and physical capabilities: Fast-paced environment. Work under pressure. Repetitive tasks. Attention to detail. Sitting. Personal suitability: Efficient interpersonal skills. Excellent oral communication. Excellent written communication. Team player. Accurate. Experience: 1 year to less than 2 years. Financial benefits: Bonus. Commission. Other benefits: Free parking available. Paid time off (volunteering or personal days).",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1695945600,
      "job_posted_at_datetime_utc": "2023-09-29T00:00:00.000Z",
      "job_city": "Mississauga",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.589046,
      "job_longitude": -79.64412,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=P9FrwFQjfz0od0DlAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-20T00:00:00.000Z",
      "job_offer_expiration_timestamp": 1703030400,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": [
        "Additional information Work conditions and physical capabilities   Fast-paced environment   Work under pressure   Repetitive tasks   Attention to detail   Sitting   Personal suitability   Efficient interpersonal skills   Excellent oral communication   Excellent written communication   Team player   Accurate"
      ],
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Ontario Power Generation",
      "employer_logo": "https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=843000419415245",
      "employer_website": "http://www.opg.com",
      "employer_company_type": "Utilities",
      "job_publisher": "Workopolis",
      "job_id": "dnV1hHao_jj7h8ibAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Web Developer",
      "job_apply_link": "https://www.workopolis.com/jobsearch/viewjob/_8kYLRO8FQC3l9a89jw2mkapwpGxv3k8Qn4Pa3gJfki-CJVTeLL4UsjWv_sQSoaV",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6147,
      "apply_options": [
        {
          "publisher": "Workopolis",
          "apply_link": "https://www.workopolis.com/jobsearch/viewjob/_8kYLRO8FQC3l9a89jw2mkapwpGxv3k8Qn4Pa3gJfki-CJVTeLL4UsjWv_sQSoaV",
          "is_direct": false
        }
      ],
      "job_description": "Location:\nPickering, ON, CA, L1W 3J2\n\nReq ID: 43024\n\nStatus: Temporary (12 months)\n\nWorking Conditions: Hybrid (3 days in office)\n\nEducation Level: 4 years year University education plus 1 year of further concentrated study in fields such as Computer Science, Business, Mathematics, Engineering, or by having the equivalent level of education.\n\nLocation: Pickering, ON\n\nShifts(s): Days\n\nTravel: No\n\nDeadline to Apply: August 6, 2023\n\nACCOMMODATIONS\n\nOPG is committed to fostering an inclusive, equitable, and accessible environment where all employees feel valued, respected, and supported. If you require accommodation during the application or interview process, please advise us as soon as possible so appropriate arrangements can be made.\n\nIf you require information in a format that is accessible to you, please contact AODA@opg.com\n\nElectrify your career and help build a brighter tomorrow.\n\nEvery generation has a challenge that defines them. At OPG, we are calling on all innovators, disruptors, thought leaders and change-makers. Join us to electrify life in one generation and build a sustainable future powered by our electricity, our ideas, and our people. Join OPG and make history.\n\nWhether you work in the skilled trades or are a business professional, a career at OPG is an opportunity to electrify your life on - and off - the job.\n\nNEW CAMPUS: In late 2024, OPG is establishing our new campus at 1908 Colonel Sam Drive, Oshawa, Ontario. The new campus will provide a cutting-edge work environment that fosters collaboration and innovation.\n\nJOB OVERVIEW\n\nOntario Power Generation (OPG) is looking for dynamic, strategic, and results-driven professional to join our team in the role of Experienced Web Developer.\n\nReporting to the Section Leader, Data Automation & Document Management, this position is responsible to create high-quality websites and web applications using the latest web development technologies and frameworks. Candidate will work closely with cross-functional teams, including designers, and product/project managers, to deliver a wide range of web development projects.\n\nThis is an exciting opportunity to work in an environment where you will contribute to OPG’s public outreach, engagement, and education efforts as part of the company’s commitment to growing its social license.\n\nKEY ACCOUNTABILITIES\n• Develop, code, and maintain complex web applications using various programming languages, frameworks, and databases.\n• Collaborate with cross-functional teams, including designers, product managers, project managers, and other developers to meet project requirements and timelines.\n• Create responsive and visually appealing web application designs optimized for different devices.\n• Conduct thorough testing and debugging of web applications to ensure optimal performance and quality.\n• Stay current with emerging web development technologies and trends and apply them when necessary.\n• Manage code repositories and collaborate with other developers using version control systems.\n• Ensure web applications are secure, accessible, and compliant with industry standards and best practices.\n• Deploy web applications on cloud platforms such as Azure Cloud.\n• Continuously improve the scalability, performance, and reliability of web applications.\n• Develop and maintain high-traffic web applications that can handle large volumes of user interactions.\n• Implement web analytics tools and frameworks to improve the performance of web applications.\n• Integrate web applications with third-party APIs and software systems to create seamless user experiences.\n• Work closely with stakeholders to understand their business requirements and develop custom web solutions tailored to their needs.\n• Adhere to industry best practices and standards to ensure web application optimization.\n• Implement agile development methodologies and participate in sprint planning, retrospectives, and daily stand-up meetings.\n• Conduct research and development activities to experiment with emerging technologies and tools to improve the development process and website features.\n• Other duties as required.\n\nEDUCATION\n• 4 years University education plus 1 year of further concentrated study in fields such as Computer Science, Business, Mathematics, Engineering, or by having the equivalent level of education.\n\nQUALIFICATIONS\n• A minimum of over 4 years and up to and including 6 years is considered necessary to gain this web development experience.\n• Proven experience developing and maintaining web applications and websites.\n• Experience with UI/UX design principles and tools\n• Experience with Azure cloud services and deployment of web applications on Azure cloud services\n• Experience with front-end frameworks and back-end technologies such as React, Angular, Vue.js, Node.js, PHP, or Ruby on Rails\n• Experience with Python-Django framework\n• Strong proficiency in C#, .NET programming languages such as ASP.NET, XML/HTML 5/CSS, Bootstrap, jQuery/JavaScript, SLDC, Cl/CD, Deployment, Multi-tenant Architecture, & Docker.\n• Experience with Web API development for web-based applications.\n• Knowledge of database systems such as MySQL, MongoDB, or PostgreSQL\n• Understanding of web development best practices and industry standards\n• Experience with creating responsive and visually appealing website designs.\n• Experience in using website and web application development tools such as version control, debuggers, and build tools.\n• Proficiency in Git for version control\n• Proficiency in JavaScript and Django unit testing frameworks is preferred.\n• Familiarity with server-side code concepts such as database fundamentals, request handling, MVC structure and API endpoints in a Django environment\n• Experience with development methodologies (e.g., Scrum, Agile, Waterfall)\n• Strong problem-solving skills and ability to work collaboratively in a team environment.\n\nThe successful candidate will exhibit uncompromising integrity and commitment to upholding corporate values, and the OPG Code of Business Conduct.\n\nWhat Makes a Career at OPG Different?\n\nAs Ontario’s largest clean energy generator, we’re building, expanding, and innovating the equipment and technology that keeps Ontario powered with clean, reliable energy.\n\nAt OPG, our values are our strengths. They are fundamental truths about our organization that don’t change:\n\nSafety – it’s our business.\n\nIntegrity – always lead with integrity.\n\nExcellence – never satisfied with good enough.\n\nInclusion – working together for powerful outcomes.\n\nInnovation - creativity accelerates possibility.\n\nHere's why OPG might just be the ideal workplace for you:\n• Exceptional range of opportunities province-wide\n• Long-term career growth and development opportunities\n• Electricity is vital to the province and OPG’s clean electricity is helping decarbonize other sectors.\n\nOur promise to you:\n• We care about the safety and the well-being of our employees. It is our utmost priority.\n• A supportive work environment where you can be your best every day.\n• Opportunities to stretch and develop.\n• Offer different ways for you to give back to communities where we operate.\n• Partner with Indigenous communities and support local businesses.\n• We support employment equity, diversity, and inclusion.\n\nAre you ready to start a career that has the power to electrify life on and off the job? Apply now.\n\nAPPLICATION PROCESS\n\nPlease submit your application online at https://jobs.opg.com/ by 11:59 PM E.S.T., August 6, 2023. OPG thanks all those who apply; however, only candidates considered for an interview will be contacted\n\n#LI-Hybrid\n\n.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1686006939,
      "job_posted_at_datetime_utc": "2023-06-05T23:15:39.000Z",
      "job_city": "Pickering",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.838413,
      "job_longitude": -79.08676,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=dnV1hHao_jj7h8ibAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": null,
      "job_offer_expiration_timestamp": null,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 72,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3",
      "job_naics_code": "22111",
      "job_naics_name": "Electric Power Generation"
    },
    {
      "employer_name": "theScore",
      "employer_logo": "https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/v1404395307/vvcucbmakaamlpwef49i.jpg",
      "employer_website": "http://www.thescore.com",
      "employer_company_type": "Information",
      "job_publisher": "LinkedIn",
      "job_id": "_x_q4TE0q8Ikfgy9AAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Senior Web Developer - Payments",
      "job_apply_link": "https://ca.linkedin.com/jobs/view/senior-web-developer-payments-at-thescore-3771752532",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.634,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://ca.linkedin.com/jobs/view/senior-web-developer-payments-at-thescore-3771752532",
          "is_direct": false
        },
        {
          "publisher": "ZipRecruiter",
          "apply_link": "https://www.ziprecruiter.com/c/Score-Media-and-Gaming-Inc./Job/Senior-Web-Developer-Payments/-in-Toronto,ON?jid=15f5a703be7429ab",
          "is_direct": false
        },
        {
          "publisher": "Itjobs.ca",
          "apply_link": "https://www.itjobs.ca/en/offer/on/toronto/senior-web-developer-payments/2e965dd9-136c-4483-9f08-397c35513f76_en/",
          "is_direct": false
        },
        {
          "publisher": "Jobs.ca",
          "apply_link": "https://www.jobs.ca/offer/senior-web-developer-payments/2e965dd9-136c-4483-9f08-397c35513f76_en/",
          "is_direct": false
        }
      ],
      "job_description": "theScore, a wholly-owned subsidiary of PENN Entertainment , empowers millions of sports fans through its digital media and sports betting products. Its media app ‘theScore’ is one of the most popular in North America, delivering fans highly personalized live scores, news, stats, and betting information from their favorite teams, leagues, and players. theScore’s sports betting app ‘theScore Bet Sportsbook & Casino’ delivers an immersive and holistic mobile sports betting and iCasino experience. theScore Bet is currently live in the Company's home province of Ontario. theScore also creates and distributes innovative digital content through its web, social and esports platforms.\n\nAbout The Role & Team\n\nAs a Senior Front-End Developer on the Payments team, you will enhance our customers' experience within theScore & ESPN BET Sportsbook platforms. Our goal is to provide the best platform for patrons to manage their funds. This role involves direct collaboration with our design, product, frontend, and backend development teams to define and deliver a first-class deposit/withdrawal experience. We iterate quickly, so you have plenty of opportunities to learn & grow technically, but more importantly, we have fun while doing it.\n\nAbout The Work\n\nAs a key member of our Accounts team with focus on front-end web stack you will:\n• Build front-end application features using modern JavaScript technologies (React, TypeScript).\n• Work with the product team to design, architect, and ship customer experience features to our amazing applications.\n• Implement polished user interfaces with the help of our design team.\n• Improve our code through refactoring and applying modern design patterns.\n• Work with other engineers through technical collaboration, discussion, and code review.\n• Solve difficult problems related to large data sets and responsive UIs.\n• Work with the team to define and improve our documentation, internal style guide, maintainability and best practices.\n• Provide mentorship to other developers on the team and even the entire organization.\n• Other duties as required\n\nAbout You\n• 5+ years experience in software development, specializing in front-end technologies\n• Strong understanding of JavaScript/TypeScript and general UX Principles. React framework experience preferred.\n• Experience with common front-end libraries around state management and API calls such as Redux, Zustand, Apollo\n• Experience with unit test and integration testing frameworks\n• Security-first mindset. Familiarity with OAuth2, OWASP mitigation techniques are a plus.\n• A solid foundation in computer science, with strong competencies in data structures, distributed systems, algorithms and software design.\n• Passionate about clean code architecture and software craftsmanship.\n• Experience with Git and GitHub or similar.\n• NICE TO HAVE: Full stack experience, designing REST, GraphQL API, relational data modeling with Postgres. Cloud deployment strategies and CI/CD pipelines.\n\nWhat We Offer\n• Competitive compensation package\n• Fun, relaxed work environment\n• Education and conference reimbursements.\n• Parental leave top up\n• Opportunities for career progression and mentoring others\n\ntheScore is committed to creating a diverse environment and is proud to be an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, gender, gender identity or expression, sexual orientation, national origin, genetics, disability or age.",
      "job_is_remote": true,
      "job_posted_at_timestamp": 1700685288,
      "job_posted_at_datetime_utc": "2023-11-22T20:34:48.000Z",
      "job_city": "Toronto",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.653225,
      "job_longitude": -79.38319,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=_x_q4TE0q8Ikfgy9AAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-22T20:34:48.000Z",
      "job_offer_expiration_timestamp": 1703277288,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 60,
        "experience_mentioned": true,
        "experience_preferred": true
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": "Senior",
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3",
      "job_naics_code": "519130",
      "job_naics_name": "Internet Publishing and Broadcasting and Web Search Portals"
    },
    {
      "employer_name": "Ontario Federation of Agriculture",
      "employer_logo": "https://ofa.on.ca/wp-content/uploads/2018/07/OFA-Benefit-Program-Logo-TM-2018.png",
      "employer_website": "http://www.ofa.on.ca",
      "employer_company_type": "Manufacturing",
      "job_publisher": "Workopolis",
      "job_id": "Fin0ZorfWlBdhx3RAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Web Developer",
      "job_apply_link": "https://www.workopolis.com/jobsearch/viewjob/lOo7Puu4xn-pHCODrGO46C1qbKwT3jP5qOCOKw_mgzzSoEPtaJev-vpnx6S1lZ-Z",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.5173,
      "apply_options": [
        {
          "publisher": "Workopolis",
          "apply_link": "https://www.workopolis.com/jobsearch/viewjob/lOo7Puu4xn-pHCODrGO46C1qbKwT3jP5qOCOKw_mgzzSoEPtaJev-vpnx6S1lZ-Z",
          "is_direct": false
        }
      ],
      "job_description": "The Ontario Federation of Agriculture (OFA) is seeking a passionate and motivated individual to join our team in the permanent, full-time position of Web Developer in the Information Technology Services department.\n\nWe are looking for a skilled web developer who will be responsible for developing and/or designing websites and web applications for our company. You will be working alongside your peers and in cross functional teams in creating, maintaining, and updating our websites and web applications.\n\nFor you to succeed in this role, you will need to be proficient in WordPress as well as JavaScript, HTML, CSS, and have solid knowledge and experience in a variety of programming languages, tools and applications.\n\nKEY POSITION RESPONSIBILITIES AND DUTIES\n\n· Website and software application designing, building, or maintaining.\n\n· Using scripting or authoring languages, management tools, content creation tools, applications, and digital media.\n\n· Conferring with teams to resolve conflicts, prioritize needs, develop content criteria, or choose solutions.\n\n· Directing or performing Website updates.\n\n· Developing or validating test routines and schedules to ensure that test cases mimic external interfaces and address all browser and device types.\n\n· Editing, writing, or designing Website content, and directing team members who produce content.\n\n· Maintaining an understanding of the latest Web applications and programming practices through education, study, and participation in conferences, workshops, and groups.\n\n· Back up files from Web sites to local directories for recovery.\n\n· Identifying problems uncovered by user feedback and testing and correcting or referring problems to appropriate personnel for correction.\n\n· Evaluating code to ensure it meets industry standards, is valid, is properly structured, and is compatible with browsers, devices, or operating systems.\n\n· Regular exposure to business stakeholders and executive management, as well as the authority and scope to apply your expertise to many interesting technical problems.\n\n· Determining user needs by analyzing technical requirements.\n\nQUALIFICATIONS\n\nEducation\n\n· Bachelor’s degree or Diploma in Computer Science or related field with a minimum 2 years of relevant development experience\n\nExperience\n\n· Web Development: 1 year (preferred)\n\n· WordPress Sites: 1 year (preferred)\n\nRequired Knowledge, Skills and Abilities\n\n· Bachelor’s degree or Diploma in Computer Science or related field with a minimum 2 years of relevant development experience.\n\n· Solid knowledge and experience in programming applications.\n\n· Proficient in JavaScript, HTML, HTML5, CSS, CSS3, jQuery, PHP, APIs.\n\n· Knowledge of WordPress websites and plugin creation\n\n· Knowledge of SQL databases including MS SQL Server and MySQL.\n\n· Knowledge of web UX, e-commerce, cross-browser compatibility, security principles, object-oriented design, web services (REST/SOAP), and multimedia content development.\n\n· Dedicated team player.\n\n· Ability to thrive in a fast-paced environment.\n\n· Solid ability in both written and verbal communication.\n\n· Knowledge of programming language and technical terminology.\n\n· Able to develop ideas and processes and clearly express them.\n\n· Strong grasp of security principles and how they apply to web and E-Commerce applications.\n\n· High degree of independent judgment.\n\n· Able to solve complex problems.\n\n· Creative thinking.\n\nWorking Environment\n\n· In-person – working office environment (OFA’s head office Guelph, Ontario) as well as out in the field as required.\n\n· Usually works a standard 35-hour work week.\n\n· Flexibility to travel in Ontario and a willingness to work outside of normal office hours when required (events, meetings etc.)\n\n· Must be able to manage frequent interruptions and multiple tasks daily.\n\nBENEFITS & REMUNERATION\n\n· Starting Salary Range:$49,500.00 to $60,000/yr. based on experience.\n\n· Work week: Hours of work – 8:30 a.m. to 4:30 p.m., Monday to Friday.\n\n· Benefits: OFA’s group benefit program three (3) months upon their Start Date.\n\n· Health care\n\n· Dental care\n\n· Vision care\n\n· Disability insurance\n\n· Employee & Family Assistance Program (EFAP)\n\n· Company events\n\n· Casual dress\n\n· Day shift\n\n· Pension Plan: OFA defined benefit Pension Plan upon completion of six months (6) of employment. The OFA pension plan is shared 50/50 responsibility between the Employer and the Employee.\n\n· Vacation: Three weeks (15 days) pro-rated yearly\n\n· Sick time: Sick leave benefits earned/accrued monthly over the course of each calendar year, and personal time as needed, as outlined and limited by policy.\n\n· Mileage Per/Km: Vehicle use will be compensated at a rate of 0.58 cents /km for work related mileage when applicable.\n\nCOVID-19 considerations\n\nIn accordance with OFA’s COVID-19 Vaccine policy, new employees are required to be fully vaccinated, (valid medical or Ontario Human Rights Code exemptions permitted), against COVID- 19 as a condition of employment.\n\nWe wish to thank all applicants in advance for their interest; however, only those who will be considered for an interview will be contacted. We are an equal opportunity employer and welcome diversity within our workforce. In accordance with the Accessibility for Ontarians with disabilities act, 2005 and Disabilities Act of Canada, upon request, accommodation will be provided throughout the recruitment, selection and/or assessment process to applicants with disabilities. Please note that we only recruit individuals who are here in Ontario and legally entitled to work in Canada.\n\nApplicants may submit their cover letter and resume, in confidence to Human Resources no later than May 5, 2023 at 4 pm directly to hr@ofa.on.ca\n\nJob Types: Full-time, Permanent\n\nSalary: $49,500.00-$60,000.00 per year\n\nBenefits:\n• Casual dress\n• Company events\n• Company pension\n• Dental care\n• Disability insurance\n• Employee assistance program\n• Extended health care\n• Life insurance\n• On-site parking\n• Paid time off\n• Vision care\n\nSchedule:\n• Day shift\n• Monday to Friday\n\nAbility to commute/relocate:\n• Guelph, ON N1C 0A1: reliably commute or plan to relocate before starting work (required)\n\nExperience:\n• JavaScript, HTML, HTML5, CSS, CSS3, jQuery, PHP, APIs: 1 year (required)\n• Web development: 1 year (preferred)\n• WordPress websites and plugin creation: 1 year (preferred)\n\nLicence/Certification:\n• Class G Licence (required)\n\nWork Location: One location\n\nApplication deadline: 2023-05-05",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1682105572,
      "job_posted_at_datetime_utc": "2023-04-21T19:32:52.000Z",
      "job_city": "Guelph",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.544804,
      "job_longitude": -80.24817,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=Fin0ZorfWlBdhx3RAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": null,
      "job_offer_expiration_timestamp": null,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 24,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": true,
        "degree_preferred": false,
        "professional_certification_mentioned": true
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3",
      "job_naics_code": "3253",
      "job_naics_name": "Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing"
    },
    {
      "employer_name": "Pack-Smart Inc. Automation",
      "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoRUCY1afU0GDP9NsvSUinwfTVCHCrYMY9eGe3&s=0",
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "l9O577InUgXubaDUAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": ".NET Web Developer",
      "job_apply_link": "https://ca.linkedin.com/jobs/view/net-web-developer-at-pack-smart-inc-automation-3772160672",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6399,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://ca.linkedin.com/jobs/view/net-web-developer-at-pack-smart-inc-automation-3772160672",
          "is_direct": false
        },
        {
          "publisher": "Trabajo.org",
          "apply_link": "https://ca.trabajo.org/job-2375-20231126-6648ce94636459a7316aed41c9d6e08e",
          "is_direct": false
        },
        {
          "publisher": "Talent.com",
          "apply_link": "https://ca.talent.com/view?id=84277f6f2adc",
          "is_direct": false
        },
        {
          "publisher": "WhatJobs",
          "apply_link": "https://en-ca.whatjobs.com/job/NET-Web-Developer/vaughan/68796254",
          "is_direct": false
        },
        {
          "publisher": "Recruit.net",
          "apply_link": "https://www.recruit.net/job/.net-web-developer-jobs/4ECD52504DB6866D",
          "is_direct": false
        },
        {
          "publisher": "Jobs Cast",
          "apply_link": "https://www.jobs-cast.com/job/lyrz9sgk/net-web-developer",
          "is_direct": false
        }
      ],
      "job_description": "Would you like to be part of our extraordinary and dynamic team that is Engineering the Impossible!\n\nWe are hiring an experienced .NET Web Developer with a passion for cutting-edge technologies.\n\nTo learn more about us, check out our videos: https://www.youtube.com/c/PackSmartSolutions/videos\n\nWhat we are looking for\n• Participate in the next generation architectural design, technology selection, development, validation and deployment.\n• Review requirements and collaborate cross functionally for work scope\n• Design and develop full stack of web application using modern technologies.\n• Design database and improve the performance of database.\n• Test and maintain software products to ensure strong functionality and optimization.\n• Create and maintain design documents, development journal, technical notes and reports.\n• Software deployment, on-site and remote technical support if needed\n\nWhat you will bring\n• BS/CS/EE or higher in computer science or related, or proof of exceptional skills in related fields, with practical engineering experience.\n• Proficient in C#, ASP.Net, .Net Core\n• Experience with React, Angular, Node.JS\n• Understanding of Object-Oriented design and practices\n• Worked with HTML, XML, CSS, SQL, JSON, RESTful API\n• Familiar with current UX/UI best practices\n• Occasional travel\n\nJoin The Pack-Smart Team because:\n• We care for YOU: We work to develop, engage, empower and energize our people through coaching, treat days, free gourmet beverages, team events and more. Endless opportunities for professional growth and development.\n• We offer competitive Total Rewards: Competitive starting salaries from $80k per year, paid vacation, comprehensive health and dental benefits including Life Insurance for self and dependents, RRSP program and numerous store discounts.\n• We offer a Modern Work Environment: A safe, dynamic and fast-paced environment where inclusion, learning and collaboration are key to successfully delivering exemplary solutions. You get the chance to work with innovative technology, advanced tools and software.\n• Our Team: We operate with a non-conventional philosophy of inter-disciplinary collaboration and innovative mindset. We wouldn’t succeed without the shared passion for making the world a more advanced place.\n\nWe welcome and encourage applications from people with disabilities. Accommodations are available on request during the hiring process.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1700770987,
      "job_posted_at_datetime_utc": "2023-11-23T20:23:07.000Z",
      "job_city": "Vaughan",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.856316,
      "job_longitude": -79.50854,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=l9O577InUgXubaDUAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-23T20:23:07.000Z",
      "job_offer_expiration_timestamp": 1703362987,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": true,
        "degree_preferred": true,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": 80000,
      "job_max_salary": 120000,
      "job_salary_currency": "CAD",
      "job_salary_period": "YEAR",
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Agilus Work Solutions",
      "employer_logo": "https://media.glassdoor.com/companyupdate/w900/701586/agilus-work-solutions-companyupdate-1644046929890.png?signature=931ecd505654c51bb8b6605349c08dcbcda0cd30da607af6399753c1cd2e3f1b",
      "employer_website": "http://www.dg.ca",
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "bBNNNNRQ90dsO3G1AAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Front End Developer",
      "job_apply_link": "https://ca.linkedin.com/jobs/view/front-end-developer-at-agilus-work-solutions-3765651931",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6318,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://ca.linkedin.com/jobs/view/front-end-developer-at-agilus-work-solutions-3765651931",
          "is_direct": false
        }
      ],
      "job_description": "Agilus is recruiting for a Front End Developer in the Financial Services industry in Hybrid.\n\nAgilus Work Solutions has a client in the financial services sector who is looking for a Front-End Developer to join their team on a permanent basis. Our client is one of the fastest growing private equity funds in North America with over $13 billion in assets. The ideal candidate will have demonstrated front-end engineering experience with the development of innovative web applications using React and Next.js, with a solid foundation in both TypeScript and JavaScript, ensuring a seamless user experience and high-performance interactions.\n\nResponsibilities\n• Develop innovative web applications using React and Next.js, with a solid foundation in both TypeScript and JavaScript, ensuring a seamless user experience and high-performance interactions\n• Collaborate effectively with backend teams, particularly those working with Python, to integrate frontend components with APIs and services\n• Implement efficient state management practices and optimize application performance to provide a responsive user interface\n• Ensure that all web applications are fully responsive and accessible (with varying roles), providing an inclusive experience for all users\n• Work closely with product managers, designers, and other stakeholders to translate requirements into high-quality front-end solutions\n• Implement robust testing frameworks and practices to ensure the reliability and the quality of the frontend code\n• Stay abreast of the latest trends and advancements in frontend development, particularly in React and Next.js, and continuously seek ways to innovate and improve processes\n• Create comprehensive documentation for frontend codebases and share knowledge and best practices with the broader engineering team\n\nRequirements\n• Degree in Computer science or Engineering\n• 3+ years of experience with at least one cloud platform (e.g., AWS, Azure, GCP). GCP preferred\n• Several years of hands-on experience developing web applications using React and Next.js, with a portfolio of completed projects having practical knowledge of TypeScript and JavaScript\n• Proficiency in Python, with experience integrating frontend components with Python-based backend services\n• Solid understanding of RESTful services and experience integrating frontend components with backend APIs\n• Expertise in creating responsive and visually appealing web pages using HTML and CSS, with a strong command of JavaScript\n• Experience with state management libraries such as Redux or Context API\n\nWhat's In It For You\n• Work with the fastest growing private equity firm in North America\n• Play an essential role in in the development of the organization’s technology stack and long-term technology-enabled strategy\n\nInterested?\n\nPlease apply directly online by email trodriguez@agilus.ca\n\nAgilus would like to thank all candidates for their interest in this opportunity. Due to the volume of resumes we receive; we may only be able to respond directly to those candidates being selected for an interview.\n\nWe encourage you to visit agilus.ca regularly or subscribe to our email alerts atagilus.ca/Account/Registeras new exciting employment opportunities become available daily.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1700855226,
      "job_posted_at_datetime_utc": "2023-11-24T19:47:06.000Z",
      "job_city": "Toronto",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.653225,
      "job_longitude": -79.38319,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=bBNNNNRQ90dsO3G1AAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-24T19:47:06.000Z",
      "job_offer_expiration_timestamp": 1703447226,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 36,
        "experience_mentioned": true,
        "experience_preferred": true
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": false,
        "degree_preferred": true,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Talentlab",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "Talentlab - CATS",
      "job_id": "czr2FVbvDEc6XLAdAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Full Stack Web Developer - Remote (Canada)",
      "job_apply_link": "https://talentlab.catsone.com/careers/88042-Talentlab/jobs/13563572-Full-Stack-Web-Developer-Remote-Canada",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6774,
      "apply_options": [
        {
          "publisher": "Talentlab - CATS",
          "apply_link": "https://talentlab.catsone.com/careers/88042-Talentlab/jobs/13563572-Full-Stack-Web-Developer-Remote-Canada",
          "is_direct": false
        }
      ],
      "job_description": "Full Stack Web Developer - Remote\n\nOur Kingston based client has been at the forefront of the insurance industry for the past 100 years, and is leading the way in digital innovation for the industry. This award-winning team strives to offer simple, fast and easy to use applications, both their end user clients, and internal stakeholders. If you're looking for an opportunity to collaborate on innovative products that will change the landscape of an entire industry, this opportunity is for you.\n\nResponsibilities include\n• Develop and deliver code to development and production environments, in support of our client's online presence and internal applications\n• Design and create content, features and Content Management System (CMS) modules in support of website administration\n• Perform quality assurance testing; detect, troubleshoot and track content and functionality defects and front end enhancement requests\n• Support administration of social media, e-commerce and SEO/marketing platforms\n• Proactively monitor applicable websites, user trends and traffic data; troubleshoot problems and ensure resolution of issues, archive and back-up content\n• Research and investigate alternate solutions for improvements; analyze and provide findings and recommendations to management\n• Perform user experience validation for sites, using site flow metrics, analytics and testing schemas\n• Maintain synchronization of production and development web servers\n\nKnowledge / Experience / Certification\n• 2-5 years work experience in a web environment with relevant code and development experience\n• Knowledge of Python, Django or Flask, as well as React.js, Node.js, and other modern JavaScript languages, libraries, and frameworks\n• Experience with development methodologies (e.g., Scrum, Agile, Waterfall) and knowledge of project management would be an asset\n• Knowledge of Google Analytics, Google Search Appliance and monitoring tools an asset\n• Experience with cloud infrastructures, SaaS, API development, and microservice architecture an asset\n\nEducation / Professional Courses\n• Completion of a College/University degree or equivalent experience\n\nInterested applicants should apply directly to nick.weiszhaar@talentlab.com - please ensure that your resume is titled with your name.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1592857511,
      "job_posted_at_datetime_utc": "2020-06-22T20:25:11.000Z",
      "job_city": "Kingston",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 44.231346,
      "job_longitude": -76.48097,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=czr2FVbvDEc6XLAdAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": null,
      "job_offer_expiration_timestamp": null,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 24,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": true,
        "degree_preferred": false,
        "professional_certification_mentioned": true
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Marketers on Demand",
      "employer_logo": null,
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LocalWork.ca",
      "job_id": "nVI7YENjJLaOF-hxAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Web Developer",
      "job_apply_link": "https://www.localwork.ca/job/8265072/web-developer/",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.5604,
      "apply_options": [
        {
          "publisher": "LocalWork.ca",
          "apply_link": "https://www.localwork.ca/job/8265072/web-developer/",
          "is_direct": false
        }
      ],
      "job_description": "Marketers on Demand is currently seeking a Web Developer for our innovative, fast-growing client! We are ideally looking for someone who will optimize their website's performance, ensure exceptional user experience and drive higher conversion rates.\n\nThis is a Hybrid role in Toronto, with 2 days a week in office.\n\nKey Responsibilities:\n\n• Oversee the end-to-end development of their website (planning, testing, and launching new pages)\n• Create custom elements within WordPress using efficient, reusable, and reliable code\n• Work collaboratively to enhance site functionality, user experience, and conversion rates\n• Engage with external development teams on various projects\n• Implement improvements that increase website performance, optimize speed, usability, and search engine rankings\n\nKey Qualifications:\n\n• Over 2 years of experience with content management systems and WordPress\n• Experience building new webpages as well as through templates\n• A strong understanding of standard web development (craft clean, reusable code in HTML, CSS and JavaScript for web experiences in a mobile-first environment)\n• Experience with website analytics (GA4) and other web integration tools (ex. GTM and Optimizely)\n• A solid understanding of technical SEO best practices (work with a content team to implement on-page SEO elements)\n\nIf interested, please apply directly or reach out to mark.brosas@marketersondemand.com for more info!",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1700629200,
      "job_posted_at_datetime_utc": "2023-11-22T05:00:00.000Z",
      "job_city": null,
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 51.253777,
      "job_longitude": -85.32321,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=nVI7YENjJLaOF-hxAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-22T05:00:00.000Z",
      "job_offer_expiration_timestamp": 1703221200,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 24,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "STEM Montessori Academy of Canada",
      "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGn2pW_6f2zGqOHrNwaujrJdi1ug2H0mm0Z5Qk&s=0",
      "employer_website": null,
      "employer_company_type": null,
      "job_publisher": "LinkedIn",
      "job_id": "SdMCseLztx5Qw4bRAAAAAA==",
      "job_employment_type": "TEMPORARY",
      "job_title": "Volunteer Web Developer",
      "job_apply_link": "https://ca.linkedin.com/jobs/view/volunteer-web-developer-at-stem-montessori-academy-of-canada-3636847262",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.6326,
      "apply_options": [
        {
          "publisher": "LinkedIn",
          "apply_link": "https://ca.linkedin.com/jobs/view/volunteer-web-developer-at-stem-montessori-academy-of-canada-3636847262",
          "is_direct": false
        },
        {
          "publisher": "Jobcanadian.com",
          "apply_link": "https://jobcanadian.com/ko/web-developer-job63237",
          "is_direct": false
        },
        {
          "publisher": "Suissemedias.net",
          "apply_link": "https://suissemedias.net/?refId=KRLbw98Fw2PUmEZYIq9UsA%3D%3D&trackingId=%2FcCJoznS%2FsgyX0qPA7HqJA%3D%3D&position=19&pageNum=0&trk=public_jobs_jserp-result_search-card&_=%2Fjobs%2Fview%2Fvolunteer-web-developer-at-stem-montessori-academy-of-canada-3636847262%23KJWqMdlUlBnoKqMZWRPrgo%2F8ds9jFFI%3D",
          "is_direct": false
        }
      ],
      "job_description": "The STEM Montessori Academy of Canada/STEM International Academy of Canada (SMAC-SIAC) is a regional STEM program open to all students with the mission to deliver top-notch STEM literacy and application. SMAC-SIAC is an inclusive STEM private school catering to all incomes.\n\nOur STEM program is the first of its kind in Canada and seeks to educate students from preschool to grade 12 (2.5 years of age to 18 years of age). SMAC-SIAC specializes in an advanced, bar-none, STEM-based educational curriculum that emphasizes the interconnected subject areas of science, technology, engineering, and math.\n\nCampus Locations\n\nToronto\n\nBrampton\n\nOttawa\n\nKitchener\n\nCambridge\n\nMilton\n\nMontreal\n\nVancouver\n\nVictoria\n\nCalgary\n\nThis position is for an immediate start. Kindly read the job description duties prior to the application. Serious inquiries only.\n\nSTEM Montessori Academy of Canada (SMAC) specializes in an advanced, bar-none STEM-based educational curriculum that emphasizes the interconnected subject areas of science, technology, engineering, and math.\n\nWe are seeking a Volunteer Web Development Team Manager to help complete our MemberPress-driven website. The project is almost complete but needs an expert in MemberPress to audit and complete.\n\nDuration 1-2 weeks - 8 - 10 hours/week\n\nDuties\n• MemberPress knowledge required\n• Web Development Developer/Manager to manage the project direction and determine steps to completion.\n• Manage all actions to be implemented during the project and ensure good communication between participants.\n• Allocates tasks to all web teams including back-end, front-end, and auditors in the early phases of the project including drafting of the specifications, defining the schedule of implementation, and the delivery dates.\n• Manage various problems encountered (unidentified technical constraints, human resources management, conflict resolution, need for material resources, etc.) in order to solve them and allow the continuity of the project.\n\nRequirements\n• STRONG knowledge of MemberPress, and working with implementation\n• STRONG technical knowledge\n• Knowledge of working with Moodle, Github, WordPress, MySQL\n• Speak effectively with both the technical team and management.\n• Highly focused, detail-oriented, and very conscientious of meeting project restraints and timelines.\n• Highly collaborative style; experience developing and marketing team.\n• Excellent writing/editing and verbal communication skills\n• A strong track record as an implementer who thrives on managing a variety of key initiatives\n• Self-starter, able to work independently; enjoys creating and implementing new initiatives\n\nOther Qualifications\n• Applicants must have an understanding of charitable and not-for-profit organizations.\n\nWhat’s in it for you?\n• volunteer hours\n• job reference letter (if required)\n• on-the-job training and experience in the field.\n• ability to assist a non-profit and impact the lives of children\n\nWe are strongly committed to equity and diversity within its community. We welcome and encourage applications from all religious backgrounds, persons of color, women, Indigenous/Aboriginal persons, persons with disabilities, and others who can contribute to the diversification of our community.\n\nInterested candidates are encouraged to submit a resume to volunteer@stemcanada.ca\n\nWe thank you for your interest in this opportunity; however, only those selected for an interview will be contacted.\n\nThis is a volunteer opportunity provided by VolunteerMatch, in partnership with LinkedIn for Good.",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1684611702,
      "job_posted_at_datetime_utc": "2023-05-20T19:41:42.000Z",
      "job_city": "Toronto",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 43.653225,
      "job_longitude": -79.38319,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=SdMCseLztx5Qw4bRAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": "2023-12-24T08:33:09.000Z",
      "job_offer_expiration_timestamp": 1703406789,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": null,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": true,
        "degree_mentioned": true,
        "degree_preferred": false,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": "Volunteer",
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3"
    },
    {
      "employer_name": "Ontario Northland",
      "employer_logo": "https://www.railwayage.com/wp-content/uploads/2012/04/Ontario-Northland-logo.jpg",
      "employer_website": "http://www.ontarionorthland.ca",
      "employer_company_type": "Logistics",
      "job_publisher": "Workopolis",
      "job_id": "AZMqDvzIgKeDjxWvAAAAAA==",
      "job_employment_type": "FULLTIME",
      "job_title": "Front-End Web Developer",
      "job_apply_link": "https://www.workopolis.com/jobsearch/viewjob/Y-DMvRz7fb1iyfhZBC1kmuyY6xbsD5_gsVZt37lJ7IoODDnEj94vMAioTjC-yps5",
      "job_apply_is_direct": false,
      "job_apply_quality_score": 0.617,
      "apply_options": [
        {
          "publisher": "Workopolis",
          "apply_link": "https://www.workopolis.com/jobsearch/viewjob/Y-DMvRz7fb1iyfhZBC1kmuyY6xbsD5_gsVZt37lJ7IoODDnEj94vMAioTjC-yps5",
          "is_direct": false
        }
      ],
      "job_description": "POSITION: Front-End Web Developer (New)\n\nREPORTS TO: Creative Services Manager\n\nDEPARTMENT: Marketing and Communications\n\nLOCATION: North Bay\n\nREFERENCE: 800-28B-24\n\nSALARY: $59,982- $70,568\n\nWHO WE ARE:\n\nOntario Northland Transportation Commission (ONTC) is an Agency of the Province of Ontario that provides efficient and vital transportation services. We employ over 900 skilled professionals and are over 120 years old and proud of our heritage and connection to the communities we serve. We are focused on moving forward with the goal of being a valued leader in transportation. We offer competitive salary, excellent benefits, a defined benefit pension plan, paid vacation, 3 paid personal leave days along with discounted transportation on our bus and passenger rail services.\n\nACCOUNTABILITY STATEMENT:\n\nThe Front-End Web Developer will ensure that the website is maintained, current, functioning, engaging, and meets industry standards. The role is responsible for central website development, which includes design, maintenance, and publishing.\n\nMAJOR DUTIES/ RESPONSIBILITIES:\n• Enhance and maintain Ontario Northland’s web presence.\n• Perform regular maintenance such as replacing images, posting service updates, schedules, blog posts, documents, and more.\n• Post new content and improve functionality to ensure a visitor has a positive and engaging experience.\n• Liaise with content stakeholders on an ongoing basis.\n• Ensures that translations are made to meet the requirements of the French Language Service Act and meet accessibility requirements.\n• Integrates third-party platforms into the website and ensures they meet brand style requirements and function properly\n• Works closely with the team to ensure all promotional campaigns have a digital presence.\n• Assists and delivers technical training to employees about how to post to the web and submit content.\n• Identify content on the website that requires updating and finds solutions by engaging other team members or external suppliers.\n• Administers and updates digital platforms (beyond the website).\n• Innovate and enhance digital systems to ensure Ontario Northland is keeping up with emerging technologies and trends.\n• Participate in projects related to the website, ensuring realistic deadlines and milestones for large projects.\n• Create reporting and metrics as they relate to the website and performance.\n• Other duties as required.\n\nREQUIREMENTS:\n• Diploma in Web design, Computer Programming or a degree in Computer Science or a related discipline\n• 3-5 years of direct work experience with web protocols, standards, and technologies\n• Training on Drupal Web Development preferred.\n• Proficiency in front-end development web programming languages such as HTML and CSS, JQuery, and JavaScript\n• Aptitude in graphic design software including Adobe Photoshop, Adobe Illustrator, and other visual design tools.\n• Understanding of content management systems (including Drupal), search engine optimization principles and of cross-browser compatibility issues\n• Understanding of emerging trends and new technologies\n• Excellent oral and written communications skills\n• Ability to solve problems creatively and effectively\n• Ability to conform to shifting priorities, demands and timelines through analytical and problem-solving capabilities\n• Knowledge in Microsoft Office, including Word and Outlook with a strong proficiency in Excel and PowerPoint\n• Bilingual (French and English) is an asset\n• Must be committed to company health and safety\n\nBACKGROUND INVESTIGATION: The successful candidate will need to pass the following clearances: criminal record check, employment references and education verification.\n\nCLOSING DATE: August 25, 2023, no later than 11:59 p.m. We thank all applicants for their interest; however, only those selected for an interview will be contacted. Qualified individuals are invited to apply in writing with a current covering letter and resume (provided in one document), stating reference name and number.\n\nOntario Northland is an equal opportunity employer. Accommodation is available for applicants with disabilities throughout the recruitment process. Please contact Human Resources.\n\nPour des renseignements en français composez le 1.800.363.7512 poste 494.\n\nK5gGjM4P6Y",
      "job_is_remote": false,
      "job_posted_at_timestamp": 1691623692,
      "job_posted_at_datetime_utc": "2023-08-09T23:28:12.000Z",
      "job_city": "North Bay",
      "job_state": "ON",
      "job_country": "CA",
      "job_latitude": 46.309116,
      "job_longitude": -79.46082,
      "job_benefits": null,
      "job_google_link": "https://www.google.com/search?gl=ca&hl=en&rciv=jb&q=web+developer+ontario&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+ontario&htidocid=AZMqDvzIgKeDjxWvAAAAAA%3D%3D",
      "job_offer_expiration_datetime_utc": null,
      "job_offer_expiration_timestamp": null,
      "job_required_experience": {
        "no_experience_required": false,
        "required_experience_in_months": 36,
        "experience_mentioned": true,
        "experience_preferred": false
      },
      "job_required_skills": null,
      "job_required_education": {
        "postgraduate_degree": false,
        "professional_certification": false,
        "high_school": false,
        "associates_degree": false,
        "bachelors_degree": false,
        "degree_mentioned": false,
        "degree_preferred": true,
        "professional_certification_mentioned": false
      },
      "job_experience_in_place_of_education": false,
      "job_min_salary": null,
      "job_max_salary": null,
      "job_salary_currency": null,
      "job_salary_period": null,
      "job_highlights": {},
      "job_job_title": null,
      "job_posting_language": "en",
      "job_onet_soc": "15113400",
      "job_onet_job_zone": "3",
      "job_naics_code": "482",
      "job_naics_name": "Rail Transportation"
    }
  ]
};

export default data;